[package]
name = "hhcc"
version = "0.0.6"
edition = "2021"
authors = ["wizard-lgtm"]
description = "Holy HolyC Compiler"
license = "MIT"


[dependencies]
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"